export const VERIFY_TRUE = 'USER/VERIFY_TRUE'

export const EMAIL = 'LOGIN/EMAIL'
export const PASSWORD = 'LOGIN/PASSWORD'
export const FINISHED_SUCCESS = 'LOGIN/FINISHED_SUCCESS'

export const EXIT = 'USER/EXIT'
export const DELETE_ACCOUNT = 'USER/DELETE_ACCOUNT'

export const ERROR = "ERROR"
export const ERROR_HIDE = "ERROR_HIDE"

export const DONE_ALERT = "DONE_ALERT/DONE_ALERT"
export const HIDE_DONE_ALERT = "DONE_ALERT/HIDE_DONE_ALERT"
    
export const REGISTER_EMAIL = 'REGISTER/REGISTER_EMAIL'
export const REGISTER_PASSWORD = 'REGISTER/REGISTER_PASSWORD'
export const REGISTER_NAME = 'REGISTER/REGISTER_NAME'
export const REGISTER_SURNAME = 'REGISTER/REGISTER_SURNAME'
export const FINISHED_REGISTER = 'LOGIN/FINISHED_REGISTER'

export const CHANGE_NAME = 'CHANGE/CHANGE_NAME'
export const CHANGE_SURNAME = 'CHANGE/CHANGE_SURNAME'


export const CREATE_POST_TITLE = 'CREATE_POST/CREATE_POST_TITLE'
export const CREATE_POST_TEXT = 'CREATE_POST/CREATE_POST_TEXT'
export const CREATE_POST_IMG = 'CREATE_POST/CREATE_POST_IMG'
export const CREATE_POST_TYPE_IMPOTENT = 'CREATE_POST/CREATE_POST_TYPE_IMPOTENT'
export const CREATE_POST_FINISHED = 'CREATE_POST/CREATE_POST_FINISHED'
export const CREATE_POST_HTML_PAGE = 'CREATE_POST/CREATE_POST_HTML_PAGE'

export const GET_ALL_POSTS = 'POSTS/GET_ALL_POSTS'
export const DELETE_POST = 'POSTS/DELETE_POST'

export const GET_ALL_POSTS_IMPOTENT = 'POSTS/GET_ALL_POSTS_IMPOTENT'
export const DELETE_POST_IMPOTENT = 'POSTS/DELETE_POST_IMPOTENT'

export const GET_NEWS_DAY = "NEWS_DAY/NEWS_DAY"

export const PAGE = "POSTS/PAGE"
export const COUNT_PAGE = "POSTS/COUNT_PAGE"
export const PAGE_NULL_IMPOTENT = 'POSTS/PAGE_NULL_IMPOTENT'

export const PAGE_IMPOTENT = "POSTS/PAGE_IMPOTENT"
export const COUNT_PAGE_IMPOTENT = "POSTS/COUNT_PAGE_IMPOTENT"
export const PAGE_NULL = 'POSTS/PAGE_NULL'

export const LOADING_TRUE = "LOADING/LOADING_TRUE"
export const LOADING_FALSE = "LOADING/LOADING_FALSE"    